apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
spec:
  selector:
    matchLabels:
      run: stress-test
  replicas: 1
  template:
    metadata:
      labels:
        run: stress-test
    spec:
      containers:
      - name: stress-test
        image: stress-test:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---

apiVersion: v1
kind: Service
metadata:
  name: stress-test
  labels:
    run: stress-test
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    run: stress-test
