apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
spec:
  selector:
    matchLabels:
      run: stress-test
  replicas: 1
  template:
    metadata:
      labels:
        run: stress-test
    spec:
      containers:
      - name: stress-test
        image: shdkej/stress-server:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: "/test"
            name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            path: /test
---

apiVersion: v1
kind: Service
metadata:
  name: stress-test
  labels:
    run: stress-test
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: stress-test
